name: sugar_tracker
description: App to track your sugar data.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  supabase_flutter: ^1.2.2
  sentry_flutter: ^6.20.1

  # Routing
  auto_route: ^5.0.4

  # Dependency Injection
  injectable: ^2.1.0
  get_it: ^7.2.0

  # Functional programming
  fpdart: ^0.3.0

  json_annotation: ^4.7.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  image_picker: ^0.8.6
  flutter_dotenv: ^5.0.2
  syncfusion_flutter_charts: ^20.3.59
  go_router: ^6.0.2
  bloc: ^8.1.0
  email_validator: ^2.1.17
  provider: ^6.0.5
  flutter_riverpod: ^2.2.0
  freezed_annotation: ^2.0.3
  google_fonts: ^4.0.3
  intl: ^0.18.0
  font_awesome_flutter: ^10.4.0
  flutter_local_notifications: ^8.2.0
  timezone: ^0.8.0
  flutter_native_timezone: ^2.0.0
  rxdart: ^0.27.7
  path_provider: ^2.0.14
  http: ^0.13.5
  loading_animation_widget: ^1.2.0+4
  rive: ^0.10.4
  flutter_markdown: ^0.6.14
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^2.0.3
  build_runner: ^2.3.2
  flutter_lints: ^2.0.1
  json_serializable: ^6.5.4
  auto_route_generator: ^5.0.3
  injectable_generator: ^2.1.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/diabetes_report.md
    - assets/.env

